### ISSUE TITLE
(aws-cloudfront-s3) Error when trying to add an edge lambda - Cannot read properties of undefined (reading 'role')

### ISSUE THREAD

**Issue by maximedemarey-wb** [awslabs/aws-solutions-constructs#1059]
I'm using CloudFrontToS3 construct and I try to configure an edgeLambda as default behavior (in order to validate some security aspects). When trying to add this edge lambda I get an error `Cannot read properties of undefined (reading 'role')`

### Reproduction Steps

lambda : 
```
this.lambdaAuthorizer = new NodejsFunction(this, 'LambdaAuthorizer', {
      entry: path.join(__dirname, 'lambda-authorizer.cloudfront.js'),
      runtime: Runtime.NODEJS_18_X,
    });

    this.lambdaAuthorizer.addPermission('LambdaPermission', {
      principal: new iam.ArnPrincipal('cloudfront.amazonaws.com'),
    });
```
cloudfront :
```
const edgeLambdas = [];
    if (props.lambdaAuthorizer) {
      const edgeLambda = {
        functionVersion: props.lambdaAuthorizer.currentVersion,
        eventType: cloudfront.LambdaEdgeEventType.ORIGIN_REQUEST,
      };
      edgeLambdas.push(edgeLambda);
    }

const cloudfrontS3 = new CloudFrontToS3(
      this,
      `${props.stageName}-frontweb-cloudfront-s3`,
      {
        cloudFrontDistributionProps: {
          domainNames: [props.domainName],
          certificate: props.acmCertificate,
          defaultBehavior: {
            edgeLambdas: [edgeLambdas],
          },
        },
      }
    );
```

### Error Log

```
TypeError: Cannot read properties of undefined (reading 'role')
    at .../node_modules/.pnpm/aws-cdk-lib@2.122.0_constructs@10.3.0/node_modules/aws-cdk-lib/aws-cloudfront/lib/private/cache-behavior.js:1:2227
    at Array.forEach (<anonymous>)
    at CacheBehavior.grantEdgeLambdaFunctionExecutionRole (.../node_modules/.pnpm/aws-cdk-lib@2.122.0_constructs@10.3.0/node_modules/aws-cdk-lib/aws-cloudfront/lib/private/cache-behavior.js:1:2168)
    at new CacheBehavior (.../node_modules/.pnpm/aws-cdk-lib@2.122.0_constructs@10.3.0/node_modules/aws-cdk-lib/aws-cloudfront/lib/private/cache-behavior.js:1:488)
    at new Distribution (.../node_modules/.pnpm/aws-cdk-lib@2.122.0_constructs@10.3.0/node_modules/aws-cdk-lib/aws-cloudfront/lib/distribution.js:1:2829)
    at Object.createCloudFrontDistributionForS3 (.../node_modules/.pnpm/@aws-solutions-constructs+core@2.49.0_aws-cdk-lib@2.122.0_constructs@10.3.0/node_modules/@aws-solutions-constructs/core/lib/cloudfront-distribution-helper.ts:163:26)
    at new CloudFrontToS3 (.../node_modules/.pnpm/@aws-solutions-constructs+aws-cloudfront-s3@2.49.0_@aws-solutions-constructs+core@2.49.0_@aws_jwial6ick6kxquuqlppejzoata/node_modules/@aws-solutions-constructs/aws-cloudfront-s3/lib/index.ts:147:58)
    at new FrontWebStack (.../apps/cdk/lib/front-web.ts:43:26)
    at createStatefulStacks (.../apps/cdk/bin/frontend.app.ts:56:3)
    at Object.<anonymous> (.../apps/cdk/bin/frontend.app.ts:23:5)
```

### Environment

  - **CDK CLI Version      : 2.122**
  - **CDK Framework Version: 2**
  - **AWS Solutions Constructs Version     : 2.49**
  - **OS                   : macOS**
  - **Language             : Typescript**

### Other

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Thanks, we'll take a look

**Comment by maximedemarey-wb** [comment]
hmm sorry I think it was a stupid mistake on my part...
edgeLambdas is already an array, and it was set in another array in defaultBehavior

i'm closing this issue. Thanks!

**Comment by biffgaut** [comment]
Thanks for letting us know - glad you've got it working!
