### ISSUE TITLE
ApiGatewayToLambda - Not able to set custom log retention on the log group

### ISSUE THREAD

**Issue by banerjeearitraPFG** [awslabs/aws-solutions-constructs#171]
While using [ApiGatewayToLambda](https://github.com/awslabs/aws-solutions-constructs/tree/main/source/patterns/@aws-solutions-constructs/aws-apigateway-lambda) construct, if you override the default retention period of the logGroupProps, the following error is thrown on performing CDK synth/diff/deploy: 
     _TypeError: Cannot read property 'rules_to_suppress' of undefined
     Subprocess exited with error 1_

### Reproduction Steps
Use the ApiGatewayToLambda construct with custom retention for logGroupProps.
```typescript
import * as cdk from '@aws-cdk/core';
import { Runtime, Code } from '@aws-cdk/aws-lambda';
import { RetentionDays } from '@aws-cdk/aws-logs';
import { ApiGatewayToLambda } from '@aws-solutions-constructs/aws-apigateway-lambda';

export class CdktestStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new ApiGatewayToLambda(this, 'sc-lambda-rest-api', {
      lambdaFunctionProps: {
        runtime: Runtime.NODEJS_14_X,
        code: Code.fromAsset(`lib/lambdas`),
        handler: 'hello-lambda.handler',
      },
      logGroupProps: {
        retention: RetentionDays.SIX_MONTHS
      }
    }); 
  }
}
```

### Error Log

```
WARN AWS_SOLUTIONS_CONSTRUCTS_WARNING:  An override has been provided for the property: retention.

C:\VSCodeSpace\cdktest\node_modules\@aws-solutions-constructs\core\lib\cloudwatch-log-group-helper.ts:55
    if (cfnLogGroup.cfnOptions.metadata?.cfn_nag.rules_to_suppress) {
                                                 ^
TypeError: Cannot read property 'rules_to_suppress' of undefined
    at Object.buildLogGroup (C:\VSCodeSpace\cdktest\node_modules\@aws-solutions-constructs\core\lib\cloudwatch-log-group-helper.ts:55:50)
    at Object.GlobalLambdaRestApi (C:\VSCodeSpace\cdktest\node_modules\@aws-solutions-constructs\core\lib\apigateway-helper.ts:175:20)
    at new ApiGatewayToLambda (C:\VSCodeSpace\cdktest\node_modules\@aws-solutions-constructs\aws-apigateway-lambda\lib\index.ts:80:43)
    at new CdktestStack (C:\VSCodeSpace\cdktest\lib\cdktest-stack-two.ts:11:5)
    at Object.<anonymous> (C:\VSCodeSpace\cdktest\bin\cdktest.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (C:\VSCodeSpace\cdktest\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (C:\VSCodeSpace\cdktest\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
Subprocess exited with error 1
```

### Environment

  - **CDK CLI Version      : 1.94.1
  - **CDK Framework Version: 1.94.1
  - **AWS Solutions Constructs Version     : 1.94.1
  - **OS                   : Windows 10
  - **Language             : Typescript

### Other

It works without any issue on removing the custom retention property.

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
This was fixed in version [1.112.0](https://github.com/awslabs/aws-solutions-constructs/compare/v1.111.0...v1.112.0)
