### ISSUE TITLE
Adding role to SqsToLambda causes Duration.toString() error

### ISSUE THREAD

**Issue by snyder-riley-pfg** [awslabs/aws-solutions-constructs#202]
adding a role to the `FunctionProps` of a `SqsToLambda` construct causes an error:
```
jsii.errors.JSIIError: Argument to Intrinsic must be a plain value object, got () => {
            throw new Error('Duration.toString() was used, but .toSeconds, .toMinutes or .toDays should have been called instead');
        }
```

### Reproduction Steps

Working code
```
sqs_lambda_vpc = aws_sqs_lambda.SqsToLambda(
    self,
    "new-account-vpc",
    dead_letter_queue_props=sqs.QueueProps(retention_period=cdk.Duration.days(14)),
    queue_props=sqs.QueueProps(visibility_timeout=cdk.Duration.seconds(90), encryption_master_key=sqs_key),
    lambda_function_props=lambda_.FunctionProps(
        runtime=lambda_.Runtime.PYTHON_3_8,
        timeout=cdk.Duration.seconds(90),
        handler="src/entrypoint.vpc_lambda_handler",
        code=lambda_.Code.asset("build"),
        log_retention=logs.RetentionDays.ONE_WEEK,
    ),
)
```

Adding a role to the props causes the error (this role will be shared with more functions in the future, which is why it is being created externally from the construct):
```
xacc_role = iam.Role(
    self,
    "CrossAccountSetup",
    role_name="pfg-infra-xacc-account-setup",
    assumed_by=iam.ServicePrincipal("lambda.amazonaws.com"),
)

xacc_role.add_managed_policy(
    iam.ManagedPolicy.from_managed_policy_arn(
        self,
        "CrossAccountSetupLambda",
        managed_policy_arn="arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    )
)

sqs_lambda_vpc = aws_sqs_lambda.SqsToLambda(
    self,
    "new-account-vpc",
    dead_letter_queue_props=sqs.QueueProps(retention_period=cdk.Duration.days(14)),
    queue_props=sqs.QueueProps(visibility_timeout=cdk.Duration.seconds(90), encryption_master_key=sqs_key),
    lambda_function_props=lambda_.FunctionProps(
        runtime=lambda_.Runtime.PYTHON_3_8,
        timeout=cdk.Duration.seconds(90),
        handler="src/entrypoint.vpc_lambda_handler",
        code=lambda_.Code.asset("build"),
        log_retention=logs.RetentionDays.ONE_WEEK,
        role=xacc_role,
    ),
)
```

### Error Log

```
+ typescript@4.3.2
added 1 package from 1 contributor and audited 1 package in 1.597s
found 0 vulnerabilities

Install aws-cdk latest
Successful install aws-cdk latest
Install requirements.txt
Successful install requirements.txt
Run cdk deploy --require-approval never  "aws-account-request-nonprd"
jsii.errors.JavaScriptError: 
  Error: Argument to Intrinsic must be a plain value object, got () => {
              throw new Error('Duration.toString() was used, but .toSeconds, .toMinutes or .toDays should have been called instead');
          }
      at new Intrinsic (/tmp/jsii-kernel-Jkgjad/node_modules/@aws-cdk/core/lib/private/intrinsic.js:25:19)
      at Function.asAny (/tmp/jsii-kernel-Jkgjad/node_modules/@aws-cdk/core/lib/token.js:129:52)
      at Function.asString (/tmp/jsii-kernel-Jkgjad/node_modules/@aws-cdk/core/lib/token.js:99:69)
      at Duration.toString (/tmp/jsii-kernel-Jkgjad/node_modules/@aws-cdk/core/lib/duration.js:225:30)
      at realTypeOf (/tmp/jsii-kernel-Jkgjad/node_modules/@aws-solutions-constructs/core/node_modules/deep-diff/index.js:117:81)
      at deepDiff (/tmp/jsii-kernel-Jkgjad/node_modules/@aws-solutions-constructs/core/node_modules/deep-diff/index.js:193:9)
      at deepDiff (/tmp/jsii-kernel-Jkgjad/node_modules/@aws-solutions-constructs/core/node_modules/deep-diff/index.js:255:15)
      at deepDiff (/tmp/jsii-kernel-Jkgjad/node_modules/@aws-solutions-constructs/core/node_modules/deep-diff/index.js:246:13)
      at deepDiff (/tmp/jsii-kernel-Jkgjad/node_modules/@aws-solutions-constructs/core/node_modules/deep-diff/index.js:255:15)
      at deepDiff (/tmp/jsii-kernel-Jkgjad/node_modules/@aws-solutions-constructs/core/node_modules/deep-diff/index.js:255:15)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 39, in <module>
    nonprd_post = AwsAccountPostStack(
  File "/usr/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/github/workspace/infra/aws_account_post_stack.py", line 92, in __init__
    sqs_lambda_vpc = aws_sqs_lambda.SqsToLambda(
  File "/usr/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/aws_solutions_constructs/aws_sqs_lambda/__init__.py", line 172, in __init__
    jsii.create(SqsToLambda, self, [scope, id, props])
  File "/usr/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 275, in create
    response = self.provider.create(
  File "/usr/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 344, in create
    return self._process.send(request, CreateResponse)
  File "/usr/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Argument to Intrinsic must be a plain value object, got () => {
            throw new Error('Duration.toString() was used, but .toSeconds, .toMinutes or .toDays should have been called instead');
        }
Subprocess exited with error 1
CDK subcommand deploy --require-approval never for stack aws-account-request-nonprd has failed. See above console output for more details.
```

### Environment

  - **CDK CLI Version      : 1.106.1**
  - **CDK Framework Version: 1.104.0**
  - **AWS Solutions Constructs Version     : 1.104.0**
  - **OS                   : ubuntu-latest (20.04) via github actions**
  - **Language             : python**

### Other

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Thanks, we'll look into this.

**Comment by biffgaut** [comment]
We're not seeing that behavior. Two people here have run your test and succeeded. Here is the code I used - the only real difference is I instantiate a key to populate sqs_key:

```

from aws_cdk import (
    aws_lambda as lambda_,
    aws_sqs as sqs,
    aws_kms as kms,
    aws_iam as iam,
    aws_logs as logs,
    core as cdk,
)

from aws_solutions_constructs import (
    aws_sqs_lambda as aws_sqs_lambda
)

class Python202Stack(cdk.Stack):

    def __init__(self, scope: cdk.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        sqs_key = kms.Key(self, "MyKey")

        xacc_role = iam.Role(
            self,
            "CrossAccountSetup",
            role_name="pfg-infra-xacc-account-setup",
            assumed_by=iam.ServicePrincipal("lambda.amazonaws.com"),
        )

        xacc_role.add_managed_policy(
            iam.ManagedPolicy.from_managed_policy_arn(
                self,
                "CrossAccountSetupLambda",
                managed_policy_arn="arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
            )
        )

        sqs_lambda_vpc = aws_sqs_lambda.SqsToLambda(
            self,
            "new-account-vpc",
            dead_letter_queue_props=sqs.QueueProps(retention_period=cdk.Duration.days(14)),
            queue_props=sqs.QueueProps(visibility_timeout=cdk.Duration.seconds(90), encryption_master_key=sqs_key),
            lambda_function_props=lambda_.FunctionProps(
                runtime=lambda_.Runtime.PYTHON_3_8,
                timeout=cdk.Duration.seconds(90),
                handler="index.handler",
                code=lambda_.Code.asset("lambda"),
                log_retention=logs.RetentionDays.ONE_WEEK,
                role=xacc_role,
            ),
        )
```

**Comment by biffgaut** [comment]
When you see odd errors like this, it's often a version issue. Are you certain that you are using 1.104.0 of all CDK and Solutions Constructs?

**Comment by biffgaut** [comment]
@snyder-riley-pfg  While we still can't reproduce this, we saw a similar issue internally that might be related to your issue.  Try making the following change in node_modules/@aws-solutions-constructs/core/lib/override-warning-service.js. It’s line 46 in my release - should be the same or very close for you. Add ‘ retentionPeriod’ to the list of prefilters:

```
const prefilters = ['maxRecordAge', 'expiration', 'transitionAfter', 'destination', 'timeout', 'retentionPeriod'];
```

Rebuild and run and let us know if that changes the behavior. If so, we'll need to update the libraries.

**Comment by biffgaut** [comment]
Following the steps for disabling property override warnings in [this article](https://docs.aws.amazon.com/solutions/latest/constructs/core.html) will probably solve your issue as well.
