### ISSUE TITLE
Issue running jsii-pacmak with v2

### ISSUE THREAD

**Issue by pohnemus** [awslabs/aws-solutions-constructs#563]
Hi - I am running into an issue running `jsii-pacmak` using the v2 solutions-constructs. It looks like the fix to this issue has been merged in to main, but we have not released a v2 update since. Any chance we have a v2 line release planned soon? Thanks much for maintaining this library.

Potential fixes:
* https://github.com/awslabs/aws-solutions-constructs/commit/5b2fe7e173039615a07aac0006a55a877f4a188c
* https://github.com/awslabs/aws-solutions-constructs/commit/8d9ecb7848613351ee0bbaa4b3758fdd1c2e0bcf

### Error Log

```
@scope/cdk-route53-cloudfront-s3: > @scope/cdk-route53-cloudfront-s3@3.0.0-beta.2-SNAPSHOT package /home/runner/work/aws-cdk-library/aws-cdk-library/packages/route53-cloudfront-s3
@scope/cdk-route53-cloudfront-s3: > jsii-pacmak
@scope/cdk-route53-cloudfront-s3: [jsii-pacmak] [WARN] Exception occurred, not cleaning up 
@scope/cdk-route53-cloudfront-s3: [jsii-pacmak] [WARN] java failed
@scope/cdk-route53-cloudfront-s3: Error: Cannot find module '@types/deep-diff'
@scope/cdk-route53-cloudfront-s3: Require stack:
@scope/cdk-route53-cloudfront-s3: - /home/runner/work/aws-cdk-library/aws-cdk-library/node_modules/jsii-pacmak/lib/util.js
@scope/cdk-route53-cloudfront-s3: - /home/runner/work/aws-cdk-library/aws-cdk-library/node_modules/jsii-pacmak/lib/packaging.js
@scope/cdk-route53-cloudfront-s3: - /home/runner/work/aws-cdk-library/aws-cdk-library/node_modules/jsii-pacmak/lib/npm-modules.js
@scope/cdk-route53-cloudfront-s3: - /home/runner/work/aws-cdk-library/aws-cdk-library/node_modules/jsii-pacmak/lib/index.js
@scope/cdk-route53-cloudfront-s3: - /home/runner/work/aws-cdk-library/aws-cdk-library/node_modules/jsii-pacmak/bin/jsii-pacmak.js
@scope/cdk-route53-cloudfront-s3: - /home/runner/work/aws-cdk-library/aws-cdk-library/node_modules/jsii-pacmak/bin/jsii-pacmak
@scope/cdk-route53-cloudfront-s3:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
@scope/cdk-route53-cloudfront-s3:     at Function.resolve (internal/modules/cjs/helpers.js:99:19)
@scope/cdk-route53-cloudfront-s3:     at Object.findDependencyDirectory (/home/runner/work/aws-cdk-library/aws-cdk-library/node_modules/jsii-pacmak/lib/util.js:18:32)
@scope/cdk-route53-cloudfront-s3:     at /home/runner/work/aws-cdk-library/aws-cdk-library/node_modules/jsii-pacmak/lib/dependency-graph.js:46:42
@scope/cdk-route53-cloudfront-s3:     at Array.map (<anonymous>)
@scope/cdk-route53-cloudfront-s3:     at real$traverseDependencyGraph (/home/runner/work/aws-cdk-library/aws-cdk-library/node_modules/jsii-pacmak/lib/dependency-graph.js:45:10)
@scope/cdk-route53-cloudfront-s3:     at async Promise.all (index 1)
@scope/cdk-route53-cloudfront-s3:     at async Object.findLocalBuildDirs (/home/runner/work/aws-cdk-library/aws-cdk-library/node_modules/jsii-pacmak/lib/target.js:76:5)
@scope/cdk-route53-cloudfront-s3:     at async /home/runner/work/aws-cdk-library/aws-cdk-library/node_modules/jsii-pacmak/lib/targets/java.js:171:29
@scope/cdk-route53-cloudfront-s3:     at async JavaBuilder.generateMavenSettingsForLocalDeps (/home/runner/work/aws-cdk-library/aws-cdk-library/node_modules/jsii-pacmak/lib/targets/java.js:173:51)
@scope/cdk-route53-cloudfront-s3: npm ERR! code ELIFECYCLE
@scope/cdk-route53-cloudfront-s3: npm ERR! errno 1
@scope/cdk-route53-cloudfront-s3: npm ERR! @scope/cdk-route53-cloudfront-s3@3.0.0-beta.2-SNAPSHOT package: `jsii-pacmak`
@scope/cdk-route53-cloudfront-s3: npm ERR! Exit status 1
@scope/cdk-route53-cloudfront-s3: npm ERR! 
@scope/cdk-route53-cloudfront-s3: npm ERR! Failed at the @scope/cdk-route53-cloudfront-s3@3.0.0-beta.2-SNAPSHOT package script.
```

### Environment

  - **CDK CLI Version      : 2.2.0
  - **CDK Framework Version: 2.2.0
  - **AWS Solutions Constructs Version     : 2.0.0
  - **OS                   : Macos 
  - **Language             : Typescript

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Thanks for the heads up - we will try to drop a release within the next 24 hours. Sorry for the inconvenience.

**Comment by biffgaut** [comment]
Solutions Constructs release 2.1.0 is complete - we expect this will address your issue.

**Comment by pohnemus** [comment]
Thank you so much @biffgaut - this fixed our issue!
