### ISSUE TITLE
deepDiff crash with Map.set overflow

### ISSUE THREAD

**Issue by ahmetsevki** [awslabs/aws-solutions-constructs#728]
Recently we introduced a construct called [cdk-monitoring-constructs](https://github.com/cdklabs/cdk-monitoring-constructs) into our stack.

At deployment time our cdk deploy gives the following error stack:

```
RangeError: Value undefined out of range for undefined options property undefined
    at Map.set (<anonymous>)
    at TokenMap.registerStringKey (/home/runner/work/hidrb/hidrb/common/temp/node_modules/.pnpm/aws-cdk-lib@2.31.0_constructs@10.1.42/node_modules/aws-cdk-lib/core/lib/private/token-map.js:1:2282)
    at /home/runner/work/hidrb/hidrb/common/temp/node_modules/.pnpm/aws-cdk-lib@2.31.0_constructs@10.1.42/node_modules/aws-cdk-lib/core/lib/private/token-map.js:1:665
    at cachedValue (/home/runner/work/hidrb/hidrb/common/temp/node_modules/.pnpm/aws-cdk-lib@2.31.0_constructs@10.1.42/node_modules/aws-cdk-lib/core/lib/private/token-map.js:1:2602)
    at TokenMap.registerString (/home/runner/work/hidrb/hidrb/common/temp/node_modules/.pnpm/aws-cdk-lib@2.31.0_constructs@10.1.42/node_modules/aws-cdk-lib/core/lib/private/token-map.js:1:613)
    at Function.asString (/home/runner/work/hidrb/hidrb/common/temp/node_modules/.pnpm/aws-cdk-lib@2.31.0_constructs@10.1.42/node_modules/aws-cdk-lib/core/lib/token.js:1:1244)
    at PolicyStatement.toString (/home/runner/work/hidrb/hidrb/common/temp/node_modules/.pnpm/aws-cdk-lib@2.31.0_constructs@10.1.42/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.js:2:5201)
    at realTypeOf (/home/runner/work/hidrb/hidrb/common/temp/node_modules/.pnpm/@aws-solutions-constructs+core@2.10.0_c0baef088e30cfa8429eec04b3bc7a37/node_modules/@aws-solutions-constructs/core/node_modules/deep-diff/index.js:117:81)
    at deepDiff (/home/runner/work/hidrb/hidrb/common/temp/node_modules/.pnpm/@aws-solutions-constructs+core@2.10.0_c0baef088e30cfa8429eec04b3bc7a37/node_modules/@aws-solutions-constructs/core/node_modules/deep-diff/index.js:193:9)
    at deepDiff (/home/runner/work/hidrb/hidrb/common/temp/node_modules/.pnpm/@aws-solutions-constructs+core@2.10.0_c0baef088e30cfa8429eec04b3bc7a37/node_modules/@aws-solutions-constructs/core/node_modules/deep-diff/index.js:246:13)
```

### Environment

  - **CDK CLI Version      :** 2.31.0
  - **CDK Framework Version:** 2.31.0
  - **AWS Solutions Constructs Version     :** 2.10.0
  - **OS                   :** MacOS
  - **Language             :** typescript

### Other

`RangeError: Value undefined out of range for undefined options property undefined` error happens when you try to add  2^24 elements to a Set/Map and comes from node:
- https://github.com/nodejs/node/issues/37320
- https://twitter.com/cmdcolin/status/1426705349743104000

I can deploy the same stack to a different account fine. The stack we have could not potentially be creating 2^24 entities/things in `PolicyStatement`, otherwise it would have failed to deploy to the other account. 
Something is happening in `deepDiff` which explodes the number of items.

--- 

This is :bug: Bug Report

**Comment by ahmetsevki** [comment]
If I export `overrideWarningsEnabled=false`, then my stack calls `token-map.ts/registerStringKey` around 3000 times.. however, if I do `overrideWarningsEnabled=true`, 6 million + times and exclusively in `PolicyStatement.toString`. 

So, it looks like the call to `deepdiff.diff` explodes in cartesian productwise here, when it comes to diffing PolicyStatements:
https://github.com/awslabs/aws-solutions-constructs/blob/a01bceca53a9a8c5fccf93967c46f467fba85b4e/source/patterns/@aws-solutions-constructs/core/lib/override-warning-service.ts#L62

**Comment by biffgaut** [comment]
It's not clear the AWS Solutions Constructs involvement in this issue. We have no association with cdk-monitoring-constructs - did you app work prior to adding that library?

Which Solutions Constructs are you using in your app? Can you include any details as to how you are instantiating them? Without more detail on how Solutions Constructs are being used in this CDK app we're limited in what assistance we can provide.

**Comment by biffgaut** [comment]
Closing this as not a Solutions Constructs issue. We suggest you open an issue on the repo for this package [here](https://github.com/cdklabs/cdk-monitoring-constructs/issues).
